version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    # Remove command override to use the CMD from Dockerfile
    ports:
      - "8000:8000"
    volumes:
    - .:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - mynetwork

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chetan
      POSTGRES_DB: UserData
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.Core.celery_worker.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
      -  /home/chetan/Downloads:/home/chetan/Downloads
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - mynetwork

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
